### ISSUE TITLE
terraform v0.12.20 environment issue?

### ISSUE THREAD

**Issue by yukki1011** [hashicorp/f5-terraform-consul-sd-webinar#7]
When executing "terraform plan" in as3 folder, I got an below error.

-----
Error: Missing required argument
  on main.tf line 7, in resource "bigip_as3" "nginx":
   7: resource "bigip_as3" "nginx" {
The argument "config_name" is required, but no definition was found.

Error: Unsupported argument
  on main.tf line 10, in resource "bigip_as3" "nginx":
  10:   tenant_name = "consul_sd"
An argument named "tenant_name" is not expected here.
-----

After changing main.tf file in as3 folder, it worked well.

[Before]
resource "bigip_as3" "nginx" {
  as3_json    = "${file("nginx.json")}"
  tenant_name = "consul_sd"
 depends_on  = [null_resource.install_as3]

[After]
resource "bigip_as3" "nginx" {
  as3_json    = "${file("nginx.json")}"
  config_name = "sample_test1"
}

Thanks

**Comment by jcspigler2010** [comment]
Second what yukki1011 said

updated main.tf to

```# deploy application using as3
resource "bigip_as3" "nginx" {
  as3_json    = "${file("nginx.json")}"
  #tenant_name = "consul_sd"
  config_name = "demo"
  depends_on  = [null_resource.install_as3]
}
```
`as3_json` and `config_name` are now required variables with the `bigip_as3` resource type

Looks like F5 has updated in their repo but its not reflective in terraform's docs

https://github.com/F5Networks/terraform-provider-bigip/blob/master/website/docs/r/bigip_as3.html.markdown

https://www.terraform.io/docs/providers/bigip/r/bigip_as3.html

**Comment by scshitole** [comment]
@yukki1011  yes there is a issue the field was changed @RavinderReddyF5  @papineni87  can you please comment is this going to be back to tenant again ?

**Comment by RavinderReddyF5** [comment]
@scshitole to address Issues reported in terraform provider: https://github.com/terraform-providers/terraform-provider-bigip/issues/232, we modified `config_name` to `tenant_name`,and respective code changes are pushed to master but the current release doesn't have this fix. We need to update the same F5 networks repo also.

So to use current release we have to go with config_name, but in coming release it will be updated to tenant_name which is in the terraform documentation.

**Comment by chen23** [comment]
I’ve removed the tenant name and made other updates that should resolve this issue.
